changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Workflow Updates
      labels:
        - workflows
    - title: General Infrastructure Updates
      labels:
        - infrastructure
    - title: New Features or Improvements
      labels:
        - enhancements
        - maintenance
    - title: Bug Fixes
      labels:
        - bug
    - title: Infrastructure Updates
      labels:
        - infrastructure
    - title: Documentation Changes
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
