#!/bin/bash

# A simple shell script that takes as input a text file of names and converts them to
# C++ constants in a header file.
# REQUIREMENTS:
#    - A text document with the names of required ROS topics.
#    - The name of an output header file
#    - Example use in command line: 
#          ./autogen_ros_topics.sh input.txt output.h

# Checks that requirements above are fulfilled.
if [ $# -ne 2 ]; then
  echo "Usage: $0 input_file output_file"
  exit 1
fi

input_file=$1
output_file=$2

echo "#ifndef AUTOGENERATED_ROS_TOPICS" > $output_file
echo "#define AUTOGENERATED_ROS_TOPICS" >> $output_file
echo "" >> $output_file

echo "// AUTOGENERATED FILE - DO NOT EDIT" >> $output_file

echo "" >> $output_file

# Reads each line in the input text document
# Generates the name of the constant in required format
# Writes to output a C++ constant with the generated name and line
while read -r line; do
  capitalized=$(echo $line | tr '[:lower:]' '[:upper:]')
  var_name="${capitalized}_TOPIC"
  echo "constexpr auto $var_name = \"$line\";" >> $output_file
done < "$input_file"

echo "" >> $output_file
echo "#endif // AUTOGENERATED_ROS_TOPICS" >> $output_file
