# Configuration that just enables the mandatory production/deployment modules and uses their defaults
can_transceiver_node:
  ros__parameters:
    enabled: true

can_transceiver_sim_node:
  ros__parameters:
    enabled: false

cached_fib_node:
  ros__parameters:
    enabled: false

local_transceiver_node:
  ros__parameters:
    enabled: true

mock_ais_node:
  ros__parameters:
    enabled: false

remote_transceiver_node:
  ros__parameters:
    enabled: true
