#!/bin/bash

# IMPORTANT: the executable file at the end of this path must match what is defined in sailbot_db's CMakeLists.txt
EXE=$ROS_WORKSPACE/build/network_systems/lib/sailbot_db/db_util

if [ -f $EXE ]; then
    $EXE
else
    echo "$EXE not found! Did you build network_systems?"
fi
